"use client";

/**
 * Minimap — renders the procedurally-generated PNG map for the seed and
 * overlays a pulsing dot at the player's current location.
 *
 * Map source: `/maps/<genre>.{png,json}` (generated by
 * backend/scripts/generate_maps.py).
 */

import { useEffect, useState } from "react";

type Loc = { name: string; x: number; y: number };
type FacL = { name: string; x: number; y: number; r: number; color: number[] };
type MapMeta = {
  width: number;
  height: number;
  name: string;
  genre: string;
  locations: Loc[];
  factions: FacL[];
};

type Props = {
  genre: string;
  /** Current location name from the latest scene. */
  currentLocation?: string;
  /** Optional click handler when a location pin is selected. */
  onPick?: (loc: Loc) => void;
  /** Trail of recent location names, used for breadcrumb dots. */
  trail?: string[];
};

export default function Minimap({ genre, currentLocation, onPick, trail = [] }: Props) {
  const [meta, setMeta] = useState<MapMeta | null>(null);

  useEffect(() => {
    let cancel = false;
    fetch(`/maps/${genre}.json`)
      .then((r) => (r.ok ? r.json() : null))
      .then((j) => { if (!cancel) setMeta(j); })
      .catch(() => { if (!cancel) setMeta(null); });
    return () => { cancel = true; };
  }, [genre]);

  if (!meta) {
    return (
      <div className="rounded-xl border border-stone-800 bg-stone-900/40
                      h-[220px] flex items-center justify-center
                      text-xs opacity-50">
        正在测绘 {genre} 地图…
      </div>
    );
  }

  const W = meta.width, H = meta.height;
  // Match player to a location by partial name (location names may differ
  // slightly between the seed and the scene's location_name fragment).
  const here = meta.locations.find(
    (l) => currentLocation && (l.name === currentLocation
                              || currentLocation.includes(l.name)
                              || l.name.includes(currentLocation)),
  );

  const trailPts = trail
    .map((nm) => meta.locations.find(
      (l) => nm === l.name || nm.includes(l.name) || l.name.includes(nm),
    ))
    .filter(Boolean) as Loc[];

  return (
    <div className="rounded-xl border border-stone-800 bg-stone-900/40
                    p-2 overflow-hidden">
      <div className="flex items-center justify-between mb-1 px-1">
        <div className="text-[11px] uppercase tracking-widest opacity-70">
          🗺 {meta.name}
        </div>
        <div className="text-[10px] opacity-50">{meta.genre}</div>
      </div>
      <div className="relative w-full" style={{ paddingTop: `${(H/W)*100}%` }}>
        <img src={`/maps/${genre}.png`}
             alt={meta.name}
             className="absolute inset-0 w-full h-full object-cover rounded-md
                        select-none pointer-events-none" draggable={false} />
        <svg viewBox={`0 0 ${W} ${H}`}
             className="absolute inset-0 w-full h-full"
             preserveAspectRatio="none">
          {/* trail breadcrumbs */}
          {trailPts.length > 1 && (
            <polyline
              points={trailPts.map((p) => `${p.x},${p.y}`).join(" ")}
              fill="none" stroke="#fcd34d" strokeOpacity="0.7"
              strokeDasharray="6 6" strokeWidth="3" />
          )}
          {trailPts.map((p, i) => (
            <circle key={i} cx={p.x} cy={p.y} r={5}
                    fill="#fcd34d" opacity={0.4 + 0.6 * (i + 1) / trailPts.length} />
          ))}
          {/* clickable hot-spots over the rendered pins */}
          {meta.locations.map((l) => (
            <g key={l.name}
               onClick={() => onPick?.(l)}
               style={{ cursor: onPick ? "pointer" : "default" }}>
              <circle cx={l.x} cy={l.y} r={20} fill="transparent" />
            </g>
          ))}
          {/* player dot */}
          {here && (
            <g>
              <circle cx={here.x} cy={here.y} r={18}
                      fill="rgba(252, 211, 77, 0.18)">
                <animate attributeName="r" values="14;26;14" dur="1.8s"
                         repeatCount="indefinite" />
                <animate attributeName="opacity" values="0.6;0.05;0.6" dur="1.8s"
                         repeatCount="indefinite" />
              </circle>
              <circle cx={here.x} cy={here.y} r={7} fill="#fcd34d"
                      stroke="#1a1306" strokeWidth="2" />
            </g>
          )}
        </svg>
      </div>
      <div className="mt-1 px-1 text-[10px] opacity-60 line-clamp-1">
        {here
          ? <>当前：<span className="text-amber-300">{here.name}</span></>
          : "尚未踏入名册地点"}
      </div>
    </div>
  );
}
